version: "3.8"

services:
  sails:
    build:
      context: .
    container_name: sailsmakr
    expose:
      - "5001"
    ports:
      - "5001:5001"
    volumes:
      - ./apps:/apps
    depends_on:
      - postgres
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./apps/static:/apps/static
    depends_on:
      - sails
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: bader
      POSTGRES_PASSWORD: Theawesomebss7441$
      POSTGRES_DB: sailsmakr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
