version: "2.2"

services:
  sails:
    build:
      context: .
    image: sailsmakr/sails:v1.0
    container_name: sailsmakr
    expose:
      - "5001"
    ports:
      - "5001:5001"
    volumes:
      - ./apps:/apps
    depends_on:
      - nginx
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
    image: sailsmakr/nginx:v1.0
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./apps/static:/apps/static
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
