version: "3.8"

services:
  sails:
    build:
      context: .
    image: expo180/sailsmakr:latest
    container_name: sailsmakr
    expose:
      - "5001"
    ports:
      - "5001:5001"
    volumes:
      - ./apps:/apps
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./apps/static:/apps/static
    depends_on:
      - sails
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
