version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_CONFIG: 'default'
    networks:
      - app-network

  electron:
    image: node:14
    volumes:
      - .:/user/apps
    working_dir: /user/apps
    depends_on:
      - flask
    command: npm start
    network_mode: host
    
networks:
  app-network:
    driver: bridge
