"""empty message

Revision ID: 37f456947869
Revises: a96f084a45ec
Create Date: 2025-04-12 13:49:30.110988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f456947869'
down_revision = 'a96f084a45ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_word', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('signature_additional_badge', sa.String(), nullable=True))
        batch_op.drop_column('signature_include_profile_picture')
        batch_op.drop_column('signature_mobile')
        batch_op.drop_column('signature_website')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_website', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('signature_mobile', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('signature_include_profile_picture', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('signature_additional_badge')
        batch_op.drop_column('signature_word')

    # ### end Alembic commands ###
