"""authorization model updated for company

Revision ID: 74a5afa6fb02
Revises: 
Create Date: 2025-04-03 13:07:54.140845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a5afa6fb02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_proof_nif', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_proof_rccm', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_company', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.drop_column('is_company')
        batch_op.drop_column('company_name')
        batch_op.drop_column('company_proof_rccm')
        batch_op.drop_column('company_proof_nif')

    # ### end Alembic commands ###
