"""additionnal user email config

Revision ID: 7ac190a5dd53
Revises: 9332d76924d2
Create Date: 2025-04-09 10:11:16.048568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac190a5dd53'
down_revision = '9332d76924d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_server', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imap_server', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('imap_port', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('imap_port')
        batch_op.drop_column('imap_server')
        batch_op.drop_column('smtp_port')
        batch_op.drop_column('smtp_server')

    # ### end Alembic commands ###
