"""email signature data

Revision ID: a96f084a45ec
Revises: 
Create Date: 2025-04-11 21:02:42.647412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96f084a45ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('signature_title', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('signature_phone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('signature_mobile', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('signature_website', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('signature_include_profile_picture', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('signature_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('signature_html')
        batch_op.drop_column('signature_include_profile_picture')
        batch_op.drop_column('signature_website')
        batch_op.drop_column('signature_mobile')
        batch_op.drop_column('signature_phone')
        batch_op.drop_column('signature_title')
        batch_op.drop_column('signature_name')

    # ### end Alembic commands ###
